<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="D:/workspace_ch/testlogin"
           tests="13"
           failures="6"
           errors="0"
           skipped="0"
           time="0.028">
  <properties />
            <testcase name="testAdd" time="0.001" classname="testsuite.CalculatorExcel">
                <failure type="java.lang.AssertionError"
                  message="did not expect to find [3.0] but found [2.0]"
              >
<![CDATA[java.lang.AssertionError: did not expect to find [3.0] but found [2.0]
  org.testng.Assert.fail(Assert.java:97)
  org.testng.Assert.failNotEquals(Assert.java:969)
  org.testng.Assert.assertEquals(Assert.java:706)
  org.testng.Assert.assertEquals(Assert.java:717)
  testsuite.CalculatorExcel.testAdd(CalculatorExcel.java:32)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:498)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
  org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570)
  org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:170)
  org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
  org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790)
  org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
  org.testng.TestRunner.privateRun(TestRunner.java:763)
  org.testng.TestRunner.run(TestRunner.java:594)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
  org.testng.SuiteRunner.run(SuiteRunner.java:304)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1146)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1067)
  org.testng.TestNG.runSuites(TestNG.java:997)
  org.testng.TestNG.run(TestNG.java:965)
  org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
  org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
      </failure>

          </testcase>
            <testcase name="testAdd" time="0.000" classname="testsuite.CalculatorExcel">
                <failure type="java.lang.AssertionError"
                  message="did not expect to find [21.0] but found [20.0]"
              >
<![CDATA[java.lang.AssertionError: did not expect to find [21.0] but found [20.0]
  org.testng.Assert.fail(Assert.java:97)
  org.testng.Assert.failNotEquals(Assert.java:969)
  org.testng.Assert.assertEquals(Assert.java:706)
  org.testng.Assert.assertEquals(Assert.java:717)
  testsuite.CalculatorExcel.testAdd(CalculatorExcel.java:32)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:498)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
  org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570)
  org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:170)
  org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
  org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790)
  org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
  org.testng.TestRunner.privateRun(TestRunner.java:763)
  org.testng.TestRunner.run(TestRunner.java:594)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
  org.testng.SuiteRunner.run(SuiteRunner.java:304)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1146)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1067)
  org.testng.TestNG.runSuites(TestNG.java:997)
  org.testng.TestNG.run(TestNG.java:965)
  org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
  org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
      </failure>

          </testcase>
            <testcase name="testAdd" time="0.002" classname="testsuite.CalculatorExcel">
                <failure type="java.lang.AssertionError"
                  message="did not expect to find [36.0] but found [37.0]"
              >
<![CDATA[java.lang.AssertionError: did not expect to find [36.0] but found [37.0]
  org.testng.Assert.fail(Assert.java:97)
  org.testng.Assert.failNotEquals(Assert.java:969)
  org.testng.Assert.assertEquals(Assert.java:706)
  org.testng.Assert.assertEquals(Assert.java:717)
  testsuite.CalculatorExcel.testAdd(CalculatorExcel.java:32)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:498)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
  org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570)
  org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:170)
  org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
  org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790)
  org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
  org.testng.TestRunner.privateRun(TestRunner.java:763)
  org.testng.TestRunner.run(TestRunner.java:594)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
  org.testng.SuiteRunner.run(SuiteRunner.java:304)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1146)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1067)
  org.testng.TestNG.runSuites(TestNG.java:997)
  org.testng.TestNG.run(TestNG.java:965)
  org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
  org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
      </failure>

          </testcase>
            <testcase name="testAdd" time="0.001" classname="testsuite.CalculatorExcel">
                <failure type="java.lang.AssertionError"
                  message="did not expect to find [22.0] but found [27.0]"
              >
<![CDATA[java.lang.AssertionError: did not expect to find [22.0] but found [27.0]
  org.testng.Assert.fail(Assert.java:97)
  org.testng.Assert.failNotEquals(Assert.java:969)
  org.testng.Assert.assertEquals(Assert.java:706)
  org.testng.Assert.assertEquals(Assert.java:717)
  testsuite.CalculatorExcel.testAdd(CalculatorExcel.java:32)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:498)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
  org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570)
  org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:170)
  org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
  org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790)
  org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
  org.testng.TestRunner.privateRun(TestRunner.java:763)
  org.testng.TestRunner.run(TestRunner.java:594)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
  org.testng.SuiteRunner.run(SuiteRunner.java:304)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1146)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1067)
  org.testng.TestNG.runSuites(TestNG.java:997)
  org.testng.TestNG.run(TestNG.java:965)
  org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
  org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
      </failure>

          </testcase>
            <testcase name="testAdd" time="0.000" classname="testsuite.CalculatorExcel">
                <failure type="java.lang.AssertionError"
                  message="did not expect to find [10.0] but found [11.0]"
              >
<![CDATA[java.lang.AssertionError: did not expect to find [10.0] but found [11.0]
  org.testng.Assert.fail(Assert.java:97)
  org.testng.Assert.failNotEquals(Assert.java:969)
  org.testng.Assert.assertEquals(Assert.java:706)
  org.testng.Assert.assertEquals(Assert.java:717)
  testsuite.CalculatorExcel.testAdd(CalculatorExcel.java:32)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:498)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
  org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570)
  org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:170)
  org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
  org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790)
  org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
  org.testng.TestRunner.privateRun(TestRunner.java:763)
  org.testng.TestRunner.run(TestRunner.java:594)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
  org.testng.SuiteRunner.run(SuiteRunner.java:304)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1146)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1067)
  org.testng.TestNG.runSuites(TestNG.java:997)
  org.testng.TestNG.run(TestNG.java:965)
  org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
  org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
      </failure>

          </testcase>
            <testcase name="testAdd" time="0.001" classname="testsuite.CalculatorExcel">
                <failure type="java.lang.AssertionError"
                  message="did not expect to find [30.0] but found [36.0]"
              >
<![CDATA[java.lang.AssertionError: did not expect to find [30.0] but found [36.0]
  org.testng.Assert.fail(Assert.java:97)
  org.testng.Assert.failNotEquals(Assert.java:969)
  org.testng.Assert.assertEquals(Assert.java:706)
  org.testng.Assert.assertEquals(Assert.java:717)
  testsuite.CalculatorExcel.testAdd(CalculatorExcel.java:32)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:498)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
  org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570)
  org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:170)
  org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
  org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790)
  org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
  org.testng.TestRunner.privateRun(TestRunner.java:763)
  org.testng.TestRunner.run(TestRunner.java:594)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
  org.testng.SuiteRunner.run(SuiteRunner.java:304)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1146)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1067)
  org.testng.TestNG.runSuites(TestNG.java:997)
  org.testng.TestNG.run(TestNG.java:965)
  org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
  org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="testAdd" time="0.020" classname="testsuite.CalculatorExcel" />
                <testcase name="testAdd" time="0.000" classname="testsuite.CalculatorExcel" />
                <testcase name="testAdd" time="0.000" classname="testsuite.CalculatorExcel" />
                <testcase name="testAdd" time="0.001" classname="testsuite.CalculatorExcel" />
                <testcase name="testAdd" time="0.001" classname="testsuite.CalculatorExcel" />
                <testcase name="testAdd" time="0.000" classname="testsuite.CalculatorExcel" />
                <testcase name="testAdd" time="0.001" classname="testsuite.CalculatorExcel" />
      
</testsuite>
